### ISSUE TITLE
Incomplete StackTrace

### ISSUE THREAD

**Issue by maybeec** [maybeec/oomph-task-fsrename#1]
I recently got an error during some of the executions of the fsrename task:

```
com.github.maybeec.oomph.task.fsrename.core.exception.FSRenameException: D:\tmp\Client-PE1.3.0\azrvisa-ide-software-neon-4.6.0-capgemini-only-2-x64\software\apache-tomcat-7.0.42
  at com.github.maybeec.oomph.task.fsrename.core.impl.FileSystemRenameUtilImpl.rename(FileSystemRenameUtilImpl.java:39)
  at com.github.maybeec.oomph.task.fsrename.impl.FSRenameTaskImpl.perform(FSRenameTaskImpl.java:304)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3021)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2949)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2930)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2861)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:555)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:681)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

The bad about this is, that I do not even know why this error occurs as you are shadowing exceptions in [FileSystemRenameUtilImpl.java#L39](https://github.com/themetalone/oomph-task-fsrename/blob/3da6e90aee7682f348f10562324268a235f479a4/task-fsrename/src/com/github/maybeec/oomph/task/fsrename/core/impl/FileSystemRenameUtilImpl.java#L39)

**Comment by themetalone** [comment]
I added the whole stacktrace to the logging output. But I fear that the Java NIO doesn't hold much of information in the exceptions
